### PR TITLE
Changes to make code thread friendly

### PR DESCRIPTION
**Pull request by Dr15Jones**
Made function static arrays just be stack arrays and changed static
bools to be std::atomic<bool>. This allows multiple threads to each
safely talk to their own copies of the objects without race conditions.

### CODE REVIEW

**Comment by Dr15Jones** [comment]
@smuzaffar @davidlange6 @lgray This should fix the recent fastjet related thread-safety problems found from Lindsey's running of helgrind.

**Comment by davidlange6** [comment]
@degano

**Comment by ghost** [comment]
@Dr15Jones @davidlange6 I've merged this change in 76X: https://github.com/cms-sw/cmsdist/pull/1745

**Comment by lgray** [comment]
@Dr15Jones once this is in a working IB I'll revert the change of
NjettinessAdder to edm::one back to edm::stream.

**Comment by Dr15Jones** [comment]
Sounds good

**Pull request merged**
