### PR TITLE
Updating to v1.020 of fastjet contrib

### PR DESCRIPTION
**Pull request by rappoccio**
(Now correctly) making master of fastjet_contrib aligned with v1.020

### CODE REVIEW

**Comment by rappoccio** [comment]
Also, can someone make a branch  "cms/v1.020" so I can push the thread-safe version?

**Comment by ghost** [comment]
@rappoccio Okay, I'm doing it now

**Comment by rappoccio** [comment]
Thanks!

**Comment by ghost** [comment]
@rappoccio it's there with the stuff included in the official package for 1.020.
Let me know if that's good for you.

**Comment by rappoccio** [comment]
Thanks, perfect. I will create the patch and push it ASAP.

**Comment by rappoccio** [comment]
Perfect, thanks. PR is #8 : https://github.com/cms-externals/fastjet-contrib/pull/8

**Pull request closed without merging**
