### PR TITLE
Update native v1.033 with the CMS additions in v1.032

### PR DESCRIPTION
**Pull request by fabiocos**
CMS additions present in v1.032 are forward ported to the origina v1.033. No conflict is implied.

### CODE REVIEW

**Comment by fabiocos** [comment]
@smuzaffar @slava77 this should be ok to prepare a cmsdist PR to test whether the problem is solved

**Comment by slava77** [comment]
I'm a bit confused by so many changes.
What was used for the base of cms-externals:cms/v1.033 ?

E.g. https://github.com/cms-externals/fastjet-contrib/blob/cms/v1.032/Nsubjettiness/AxesFinder.cc is in v1.032 already but it also shows up in the diffs of this PR

**Comment by smuzaffar** [comment]
cms/v1.033 was created from http://fastjet.hepforge.org/contrib/downloads/fjcontrib-1.033.tar.gz

**Comment by smuzaffar** [comment]
I am merging it now and creating a cmsdist PR.

**Comment by slava77** [comment]
> cms/v1.033 was created from http://fastjet.hepforge.org/contrib/downloads/fjcontrib-1.033.tar.gz

OK, but then at best this PR is pretty confusing because apparently it also includes changes from v1.026 (? my guess) to 1.033. It is hard to understand what  was actually changed.

E.g. a diff of the base of 1.033 to the head 
https://github.com/cms-externals/fastjet-contrib/compare/f16517fb133aeefd6ba10627a37208b2d0a6d947...1ab32a0f646781c2104f52121172a8d3c3507125
shows Nsubjettiness/NjettinessDefinition.hh as new, while the file is actually unchanged between 1.032 and 1.033 (the file was not present in our older version v1.026)

**Comment by smuzaffar** [comment]
@slava77 , yes something does not look right. The commit https://github.com/cms-externals/fastjet-contrib/commit/e0eb40f1bac4e9afa2a6e94b9deb66c023a967ba (Updating to 1.032) does not match with the contents of fjcontrib-1.032.tar.gz file. Difference between checkout of this commit and tar.gz file shows following differences
```
diff -Naur --exclude .git v1.032 x/fjcontrib-1.032 | grep '^diff '
diff -Naur --exclude .git v1.032/Nsubjettiness/AxesFinder.cc x/fjcontrib-1.032/Nsubjettiness/AxesFinder.cc
diff -Naur --exclude .git v1.032/Nsubjettiness/AxesFinder.hh x/fjcontrib-1.032/Nsubjettiness/AxesFinder.hh
diff -Naur --exclude .git v1.032/Nsubjettiness/MeasureFunction.cc x/fjcontrib-1.032/Nsubjettiness/MeasureFunction.cc
diff -Naur --exclude .git v1.032/Nsubjettiness/MeasureFunction.hh x/fjcontrib-1.032/Nsubjettiness/MeasureFunction.hh
diff -Naur --exclude .git v1.032/Nsubjettiness/NjettinessDefinition.cc x/fjcontrib-1.032/Nsubjettiness/NjettinessDefinition.cc
diff -Naur --exclude .git v1.032/Nsubjettiness/NjettinessDefinition.hh x/fjcontrib-1.032/Nsubjettiness/NjettinessDefinition.hh
diff -Naur --exclude .git v1.032/Nsubjettiness/WinnerTakeAllRecombiner.cc x/fjcontrib-1.032/Nsubjettiness/WinnerTakeAllRecombiner.cc
diff -Naur --exclude .git v1.032/Nsubjettiness/WinnerTakeAllRecombiner.hh x/fjcontrib-1.032/Nsubjettiness/WinnerTakeAllRecombiner.hh
```

@fabiocos , the patches we had on top of v1.026 are available here https://github.com/cms-externals/fastjet-contrib/commits/cms/v1.026 .
I think all we need on top on v1.033 are
- Removed use of static in DefaultMeasure::UpdateAxesFast: https://github.com/cms-externals/fastjet-contrib/commit/b585e418a5564cd1128a3ec09ed29d32db5f99fe 
- thread safety patch: https://github.com/cms-externals/fastjet-contrib/commit/63154ae21b8f40acfb4ee163ac720c39e260aabe

**Comment by fabiocos** [comment]
@smuzaffar @slava77 what I did was to check for the difference between the CMS v1.032 and the native v1.032, and apply it on top the v1.033 added by Shahzad, that was the native one:

Only in external/fastjet-contrib/: .git
diff -r fjcontrib-1.032/JetCleanser/JetCleanser.cc external/fastjet-contrib/JetCleanser/JetCleanser.cc
32a33,34
> #if __cplusplus >= 201103L
> #else
33a36
> #endif 
diff -r fjcontrib-1.032/JetCleanser/JetCleanser.hh external/fastjet-contrib/JetCleanser/JetCleanser.hh
107a108,112
> //CMS change:
> // Change not endorsed by fastjet collaboration
> #if __cplusplus >= 201103L
>   static constexpr double jc_zero = 1.0e-6;
> #else
108a114
> #endif 
Only in external/fastjet-contrib/Nsubjettiness: AxesFinder.cc
Only in external/fastjet-contrib/Nsubjettiness: AxesFinder.hh
diff -r fjcontrib-1.032/Nsubjettiness/MeasureDefinition.cc external/fastjet-contrib/Nsubjettiness/MeasureDefinition.cc
387,388c387,388
<    static LightLikeAxis new_axes[N];
<    static fastjet::PseudoJet new_jets[N];
---
>    LightLikeAxis new_axes[N];
>    fastjet::PseudoJet new_jets[N];
Only in external/fastjet-contrib/Nsubjettiness: MeasureFunction.cc
Only in external/fastjet-contrib/Nsubjettiness: MeasureFunction.hh
Only in external/fastjet-contrib/Nsubjettiness: NjettinessDefinition.cc
Only in external/fastjet-contrib/Nsubjettiness: NjettinessDefinition.hh
Only in external/fastjet-contrib/Nsubjettiness: WinnerTakeAllRecombiner.cc
Only in external/fastjet-contrib/Nsubjettiness: WinnerTakeAllRecombiner.hh
diff -r fjcontrib-1.032/RecursiveTools/RecursiveSymmetryCutBase.cc external/fastjet-contrib/RecursiveTools/RecursiveSymmetryCutBase.cc
40c40
< bool RecursiveSymmetryCutBase::_verbose = false;
---
> std::atomic<bool> RecursiveSymmetryCutBase::_verbose {false};
diff -r fjcontrib-1.032/RecursiveTools/RecursiveSymmetryCutBase.hh external/fastjet-contrib/RecursiveTools/RecursiveSymmetryCutBase.hh
39a40,41
> #include <atomic>
> 
218c220
<   static bool _verbose;
---
>   static std::atomic<bool> _verbose;

The first commit corresponds to the differences between CMS v1.032 and original version in files already existing in the original, the second commit corresponds to the files that were adedd on top of the original version.

**Comment by smuzaffar** [comment]
@fabiocos , I think our v1.032 branch was not in the correct state.

**Comment by fabiocos** [comment]
since the new branch is created from a fresh import of a tarball, it has no history shared with the branch of the older version. I guess that this is the reason why it was not possible to change the target branch of my initial PR. I had the same problem while working in my working area. Because of this, I checked the differences between our version v1.032 and the native v1.032 from the repository, verified that they were unrelated to the differences between the native v1.032 and v1.0322, and merged them. Probably having the differences as a patch applied in cmsdist might make all this more transparent (but the patch should be modified in case of clashes with new developments in the original version).

**Comment by fabiocos** [comment]
@smuzaffar well, this is a different story, if our c,s/v1.032 branch was incorrect we had a problem that was unrelated to the memory leak. But at this point I think that Sal or Slava should say what has to enter on top of the new version, I assumed we were ok with our previous v1.032 as it was approved and merged.

**Comment by slava77** [comment]
On 3/10/18 8:04 AM, Fabio Cossutti wrote:
> @smuzaffar <https://github.com/smuzaffar> @slava77
> <https://github.com/slava77> what I did was to check for the difference
> between the CMS v1.032 and the native v1.032, and apply it on top the
> v1.033 added by Shahzad, that was the native one:
> 
> Only in external/fastjet-contrib/: .git
> diff -r fjcontrib-1.032/JetCleanser/JetCleanser.cc
> external/fastjet-contrib/JetCleanser/JetCleanser.cc
> 

OK.
Checking this apparently requires code checkout and command line diff to
make a comparison.
I'd try to avoid this if possible for git PRs that claim to be just
small changes but actually display a lot.

**Comment by smuzaffar** [comment]
@slava77 , PR displays the actual changes. commit https://github.com/cms-externals/fastjet-contrib/pull/16/commits/be4eb1b73c6f8163852824b0a6ff01ff9cd1d228 bring in the additional file. @rappoccio can you please confirm these additional files are needed on top of v1.033 tag?

**Comment by fabiocos** [comment]
@slava77 @smuzaffar @rappoccio I understand that the PR is ok for Sal, see

https://github.com/cms-sw/cmsdist/pull/3830#issuecomment-372307516

so I would move on with the merge this for tonight IB

**Comment by rappoccio** [comment]
Hi, Folks,

I had tried to retain some git history when I created the 1.032 branch, apparently it left some deprecated files in the "Nsubjettiness" folder. I don't think there is any particular harm in keeping them, they are not used. Otherwise we can mark them for deletion in the future.

Cheers,
Sal

**Comment by smuzaffar** [comment]
I suggest to remove them now so that we do not have to worry about them in future. I will update the v1.033 branch to have bare v1.033 + https://github.com/cms-externals/fastjet-contrib/pull/16/commits/69e835bfc3d36adfe70a1355a2773bc05d9f5599

and what about this patch https://github.com/cms-externals/fastjet-contrib/commit/b585e418a5564cd1128a3ec09ed29d32db5f99fe ? is it already part of v1.033 or we have to get this in too?

**Comment by fabiocos** [comment]
@rappoccio well, if they are not needed any more better that we make immediately the cleaning, as we are still in time

**Comment by smuzaffar** [comment]
@fabiocos , I will take care if it. I just wanted to know if https://github.com/cms-externals/fastjet-contrib/commit/b585e418a5564cd1128a3ec09ed29d32db5f99fe is also needed?

**Comment by smuzaffar** [comment]
ok looks like https://github.com/cms-externals/fastjet-contrib/commit/b585e418a5564cd1128a3ec09ed29d32db5f99fe is already taken care here https://github.com/cms-externals/fastjet-contrib/pull/16/commits/69e835bfc3d36adfe70a1355a2773bc05d9f5599#diff-caaa4b3a0228ce8f3cdd17f06668b7c3L387

**Comment by fabiocos** [comment]
@smuzaffar the removal of the static statement is already in the code I have committed, based on v1.032, the removal of the intialization is not.

**Comment by smuzaffar** [comment]
thanks for the confirmation. I have updated the cms/v1.033 branch and cmsdist PR. jenkins tests are running now, I will merge it once tests are passed.

**Comment by rappoccio** [comment]
OK, this looks reasonable to me.

**Pull request merged**
